const DATE_FORMATS = {
	'yyyy/MM/dd': 'yyyy/MM/dd',
	'd/M/yyyy': 'd/M/yyyy',
	'dd/MM/yyyy': 'dd/MM/yyyy',
	'dd-MM-yyyy': 'dd-MM-yyyy',
	'dd/MM/yy': 'dd/MM/yy',
	'dd.MM.yyyy': 'dd.MM.yyyy',
	'dd.MM.yy': 'dd.MM.yy',
	'dd.M.yyyy': 'dd.M.yyyy',
	'dd-MM-yy': 'dd-MM-yy',
	'yyyy/M/d': 'yyyy/M/d',
	'd.M.yyyy': 'd.M.yyyy',
	'd. M. yyyy': 'd. M. yyyy',
	'MM/dd/yyyy': 'MM/dd/yyyy',
	'd/MM/yyyy': 'd/MM/yyyy',
	'M/d/yyyy': 'M/d/yyyy',
	'd.MM.yyyy': 'd.MM.yyyy',
	'yyyy-MM-dd': 'yyyy-MM-dd',
	'd-M-yyyy': 'd-M-yyyy',
	'd.M.yyyy.': 'd.M.yyyy.',
	'yyyy. MM. dd.': 'yyyy. MM. dd.',
	'yyyy. MM. dd': 'yyyy. MM. dd',
	'yyyy.MM.dd': 'yyyy.MM.dd',
	'yyyy.MM.dd.': 'yyyy.MM.dd.',
	'yy.MM.dd': 'yy.MM.dd',
	'MM.dd.yyyy': 'MM.dd.yyyy',
	'yyyy-M-d': 'yyyy-M-d',
	'dd/MM yyyy': 'dd/MM yyyy',
};

export default DATE_FORMATS;
